Add showTrend to Question
JupiterOne/terraform-provider-jupiterone pull request #173
Opened 2023-06-07 21:58 UTC by MartinodF

This PR exposes the `showTrend` field on the Question object, allowing terraform users to read and update its value.
I've added basic tests for reading it (no update needed to cassettes, as they already contained it) and for validating it as a proper boolean.

While re-generating the GraphQL client and related docs to add `showTrend`, a couple of additional fields and values were also updated:
- `questionName` was removed from Rule
- `trigger_on_new_only` was added to Rule
- `FIFTEEN_MINUTES` was added as an acceptable value for SchedulerPollingInterval

Those changes are in a separate commit in case you want to exclude them.

2023-08-02 18:33 UTC, chrichts requested changes
@MartinodF - first off thank you for making these changes and sorry for taking so long to get back to you on this. If you have time, can you make the changes required, otherwise I can close this PR and resubmit a new PR with the required changes.

I've left 2 comments. To your point, lets exclude the PR making changes to the rule resource. This is subject to change again very soon. Besides the comments in the code, the following two functions also need to be updated (both in `resource_question.go`): `BuildQuestion` and `BuildCreateQuestionInput`. We need to add the `ShowTrend` variable to the question input. So the changes should look like:

```
func (qm *QuestionModel) BuildQuestion() client.QuestionUpdate {
	q := client.QuestionUpdate{
		Title:           qm.Title.ValueString(),
		Description:     qm.Description.ValueString(),
		Tags:            qm.Tags,
		ShowTrend:       qm.ShowTrend.ValueBool(),
		PollingInterval: client.SchedulerPollingInterval(qm.PollingInterval.ValueString()),
	}
``` 

and

```
func (qm *QuestionModel) BuildCreateQuestionInput() client.CreateQuestionInput {
	q := client.CreateQuestionInput{
		Title:           qm.Title.ValueString(),
		Description:     qm.Description.ValueString(),
		PollingInterval: client.SchedulerPollingInterval(qm.PollingInterval.ValueString()),
		ShowTrend:       qm.ShowTrend.ValueBool(),
		Tags:            qm.Tags,
	}
```

Let me know if you have any questions.

2023-08-02 18:33 UTC, chrichts commented on docs/resources/question.md
> +- `show_trend` (Boolean) Whether to enable daily trend data collection. Defaults to false.
Maybe just update "daily trend data" to trend data, because its dependant on the polling interval and won't always be daily.

2023-08-02 18:33 UTC, chrichts commented on jupiterone/internal/client/generated.go
> +	SchedulerPollingIntervalDisabled       SchedulerPollingInterval = "DISABLED"
Let exclude this, its rule related and I know subject to change.

2023-08-02 20:04 UTC, MartinodF commented
Hey Chad, thank you for the feedback.

I've applied the requested changes:
- Removed changes related to the Rule resource
- Replaced "daily trend data" with "trend data"
- Provided `ShowTrend` value in both `CreateQuestionInput` and `QuestionUpdate`

Let me know if there's anything else that needs to be addressed!

2023-08-02 21:36 UTC, chrichts commented
Looks good thanks @MartinodF, one last thing and then I can approve, can you run a `go fmt` there is an extra white space in `generated.go`.

2023-08-02 21:40 UTC, MartinodF commented
You are right. I did run `make fmt`, then didn't add the whitespace change to the commit because it seemed unrelated and I couldn't figure out it was the formatter removing an extra space. Done 🙂

2023-08-02 21:40 UTC, chrichts approved these changes

2023-08-03 03:09 UTC, i5o approved these changes

2023-08-03 17:48 UTC, zemberdotnet approved these changes

2023-08-03 17:48 UTC, merged